#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path("../lib", __FILE__)

require 'double_transposition'

cipher = Ciphers::DoubleTransposition.new

if ARGV[0] == 'encode'
  puts cipher.encipher(ARGV[1], ARGV[2], ARGV[3])
else
  puts cipher.decipher(ARGV[1], ARGV[2], ARGV[3])
end
